.TH COINFLIP "1" "September 2007" "coinflip 1.0" "Enterprise decision management system"
.SH NAME
coinflip \- decision finder
.SH SYNOPSIS
.B coinflip
.SH DESCRIPTION
Flips a coin. Output (1) sigifies heads, (*) siginfies tails.
.SH "REPORTING BUGS"
Report bugs to <becker (at) mathematik.uni-marburg.de>.
.SH COPYRIGHT
coinflip is subject to a variant of the MIT X11 license, see 
the LICENSE file
.br
This is free software.  There is NO WARRANTY, to the extent permitted by law.
